### ISSUE TITLE
Incorrect verbage?

### ISSUE THREAD

**Issue by graywolf336** [permitio/docs#330]
https://github.com/permitio/docs/blob/11d18ffcdb0729b6dff2124e7d4fe1a071633208/docs/how-to/ownership.mdx?plain=1#L110

Is this correct? Shouldn't it read:
```
As `folder` is set as parent of `file`, all permissions set on a `folder` will automatically propagate to `files` within those folders as well. 
```

I think the first reference to folder and file are incorrectly flipped.

**Comment by orweis** [comment]
You are very clearly correct.
Would you like to open this as a quick PR for the open-source contribution creds? (Otherwise I'd fix it myself)
