### ISSUE TITLE
Tabs in code snippets are hard to read in light mode

### ISSUE THREAD

**Issue by ericmand** [permitio/docs#462]
The TabTheme seems broken in light mode. 
![image](https://github.com/user-attachments/assets/064e5659-d330-45b0-af7d-5490538212fc)
The above tabs (in light mode) are hard to read but if I switch to dark mode it is fine:
![image](https://github.com/user-attachments/assets/49c31816-e995-4236-9b59-e2d5773d1dfa)

**Comment by orweis** [comment]
Thanks @ericmand !
@filipermit - please take a look

**Comment by ericmand** [comment]
Here are 4 screenshots on mobile 2 from Chrome, 2 from Brave, all from this
page: https://docs.permit.io/modeling/google-drive

**Comment by filipermit** [comment]
Hi @ericmand - I've found the bug and released the fix. Thanks for letting us know!
